# apiVersion: v1
# kind: Namespace
# metadata:
#   name: back-end

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  # namespace: back-end
  labels:
    backend: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: flaskapi
  template:
    metadata:
      name: api-pods
      # namespace: back-end
      labels:
        backend: flaskapi
    spec:
      containers:
        - name: back-end
          image: egemmell/example-back-end #changed the image name from egemmell/playability-back-end
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: db_host
              value: "10.118.0.2"
            - name: db_port
              value: "5432"
            - name: db_root_password
              value: "postgres"
            - name: app_host
              value: "0.0.0.0"

---
apiVersion: v1
kind: Service
metadata:
  name: back-end-svc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: 797a480f-949b-499f-a1e7-162379e57bc9
    service.beta.kubernetes.io/do-loadbalancer-protocol: https
  # labels:
  #   backend: flaskapi
spec:
  type: LoadBalancer
  selector:
    backend: flaskapi
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: https
